/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppContent: typeof import('./components/AppContent.vue')['default']
    DevSpace: typeof import('./components/DevSpace.vue')['default']
    DocsLeftMenu: typeof import('./components/DocsLeftMenu.vue')['default']
    DocsSubMenu: typeof import('./components/DocsSubMenu.vue')['default']
    DocsTopMenu: typeof import('./components/DocsTopMenu.vue')['default']
    HomeFooter: typeof import('./components/HomeFooter.vue')['default']
    HomeMenu: typeof import('./components/HomeMenu.vue')['default']
    LeftMenu: typeof import('./components/LeftMenu.vue')['default']
    MarkdownDisplay: typeof import('./components/MarkdownDisplay.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NMenu: typeof import('naive-ui')['NMenu']
    NPopover: typeof import('naive-ui')['NPopover']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopMenu: typeof import('./components/TopMenu.vue')['default']
    UserInfoGrid: typeof import('./components/UserInfoGrid.vue')['default']
  }
}
